//
//  SecondHouse.swift
//  animation and drawing
//
//  Created by Георгий Кузнецов on 31.05.2022.
//

import SwiftUI

struct NYcity: View {
    @Binding var cityColor: Color
    var dark : Bool
    let x: Int
    let y: Int
    var opacity: Double
    var body: some View {
        VStack {
        Path {path in
            path.move(to: CGPoint(x: 0 * x, y: 0 * y))
                      path.addLine(to: CGPoint(x: 0 * x, y: -2 * y))
                      path.addLine(to: CGPoint(x: 13 * x, y: -2 * y))
                      path.addLine(to: CGPoint(x: 13 * x, y: -24 * y))
                      path.addLine(to: CGPoint(x: 16 * x, y: -24 * y))
                      path.addLine(to: CGPoint(x: 16 * x, y: -28 * y))
                      path.addLine(to: CGPoint(x: 21 * x, y: -33 * y))
                      path.addLine(to: CGPoint(x: 24 * x, y: -30 * y))
                      path.addLine(to: CGPoint(x: 24 * x, y: -19 * y))
                      path.addLine(to: CGPoint(x: 26 * x, y: -19 * y))
                      path.addLine(to: CGPoint(x: 26 * x, y: -50 * y))
                      path.addLine(to: CGPoint(x: 32 * x, y: -53 * y))
                      path.addLine(to: CGPoint(x: 32 * x, y: -55 * y))
                      path.addLine(to: CGPoint(x: 34 * x, y: -55 * y))
                      path.addLine(to: CGPoint(x: 34 * x, y: -53 * y))
                      path.addLine(to: CGPoint(x: 40 * x, y: -50 * y))
                      path.addLine(to: CGPoint(x: 40 * x, y: -25 * y))
                      path.addLine(to: CGPoint(x: 51 * x, y: -25 * y))
                      path.addLine(to: CGPoint(x: 51 * x, y: -35 * y))
                      path.addLine(to: CGPoint(x: 54 * x, y: -38 * y))
                      path.addLine(to: CGPoint(x: 54 * x, y: -86 * y))
                      path.addLine(to: CGPoint(x: 56 * x, y: -86 * y))
                      path.addLine(to: CGPoint(x: 56 * x, y: -92 * y))
                      path.addLine(to: CGPoint(x: 58 * x, y: -92 * y))
                      path.addLine(to: CGPoint(x: 58 * x, y: -100 * y))
                      path.addLine(to: CGPoint(x: 60 * x, y: -100 * y))
                      path.addLine(to: CGPoint(x: 60 * x, y: -110 * y))
                      path.addLine(to: CGPoint(x: 61 * x, y: -110 * y))
                      path.addLine(to: CGPoint(x: 61 * x, y: -119 * y))
                      path.addLine(to: CGPoint(x: 62 * x, y: -119 * y))
                      path.addLine(to: CGPoint(x: 62 * x, y: -127 * y))
                      path.addLine(to: CGPoint(x: 61 * x, y: -127 * y))
                      path.addLine(to: CGPoint(x: 61 * x, y: -130 * y))
                      path.addLine(to: CGPoint(x: 62 * x, y: -130 * y))
                      path.addLine(to: CGPoint(x: 62 * x, y: -145 * y))
                      path.addLine(to: CGPoint(x: 63 * x, y: -145 * y))
                      path.addLine(to: CGPoint(x: 63 * x, y: -130 * y))
                      path.addLine(to: CGPoint(x: 64 * x, y: -130 * y))
                      path.addLine(to: CGPoint(x: 64 * x, y: -127 * y))
                      path.addLine(to: CGPoint(x: 63 * x, y: -127 * y))
                      path.addLine(to: CGPoint(x: 63 * x, y: -119 * y))
                      path.addLine(to: CGPoint(x: 64 * x, y: -119 * y))
                      path.addLine(to: CGPoint(x: 64 * x, y: -110 * y))
                      path.addLine(to: CGPoint(x: 65 * x, y: -110 * y))
                      path.addLine(to: CGPoint(x: 65 * x, y: -100 * y))
                      path.addLine(to: CGPoint(x: 67 * x, y: -100 * y))
                      path.addLine(to: CGPoint(x: 67 * x, y: -92 * y))
                      path.addLine(to: CGPoint(x: 69 * x, y: -92 * y))
                      path.addLine(to: CGPoint(x: 69 * x, y: -86 * y))
                      path.addLine(to: CGPoint(x: 71 * x, y: -86 * y))
                      path.addLine(to: CGPoint(x: 71 * x, y: -38 * y))
                      path.addLine(to: CGPoint(x: 74 * x, y: -35 * y))
                      path.addLine(to: CGPoint(x: 74 * x, y: -29 * y))
                      path.addLine(to: CGPoint(x: 75 * x, y: -29 * y))
                      path.addLine(to: CGPoint(x: 75 * x, y: -16 * y))
                      path.addLine(to: CGPoint(x: 77 * x, y: -16 * y))
                      path.addLine(to: CGPoint(x: 77 * x, y: -19 * y))
                      path.addLine(to: CGPoint(x: 79 * x, y: -22 * y))
                      path.addLine(to: CGPoint(x: 79 * x, y: -41 * y))
                      path.addLine(to: CGPoint(x: 84 * x, y: -41 * y))
                      path.addLine(to: CGPoint(x: 84 * x, y: -49 * y))
                      path.addLine(to: CGPoint(x: 87 * x, y: -52 * y))
                      path.addLine(to: CGPoint(x: 89 * x, y: -52 * y))
                      path.addLine(to: CGPoint(x: 90 * x, y: -66 * y))
                      path.addLine(to: CGPoint(x: 91 * x, y: -52 * y))
                      path.addLine(to: CGPoint(x: 93 * x, y: -52 * y))
                      path.addLine(to: CGPoint(x: 96 * x, y: -49 * y))
                      path.addLine(to: CGPoint(x: 96 * x, y: -41 * y))
                      path.addLine(to: CGPoint(x: 101 * x, y: -41 * y))
                      path.addLine(to: CGPoint(x: 101 * x, y: -22 * y))
                      path.addLine(to: CGPoint(x: 104 * x, y: -19 * y))
                      path.addLine(to: CGPoint(x: 104 * x, y: -16 * y))
                      path.addLine(to: CGPoint(x: 106 * x, y: -16 * y))
                      path.addLine(to: CGPoint(x: 106 * x, y: -23 * y))
                      path.addLine(to: CGPoint(x: 108 * x, y: -23 * y))
                      path.addLine(to: CGPoint(x: 108 * x, y: -95 * y))
                      path.addLine(to: CGPoint(x: 110 * x, y: -95 * y))
                      path.addLine(to: CGPoint(x: 110 * x, y: -102 * y))
                      path.addLine(to: CGPoint(x: 112 * x, y: -102 * y))
                      path.addLine(to: CGPoint(x: 112 * x, y: -110 * y))
                      path.addLine(to: CGPoint(x: 114 * x, y: -110 * y))
                      path.addLine(to: CGPoint(x: 114 * x, y: -120 * y))
                      path.addLine(to: CGPoint(x: 116 * x, y: -120 * y))
                      path.addLine(to: CGPoint(x: 116 * x, y: -130 * y))
                      path.addLine(to: CGPoint(x: 117 * x, y: -131 * y))
                      path.addLine(to: CGPoint(x: 123 * x, y: -133 * y))
                      path.addLine(to: CGPoint(x: 124 * x, y: -156 * y))
                      path.addLine(to: CGPoint(x: 125 * x, y: -133 * y))
                      path.addLine(to: CGPoint(x: 131 * x, y: -131 * y))
                      path.addLine(to: CGPoint(x: 132 * x, y: -130 * y))
                      path.addLine(to: CGPoint(x: 132 * x, y: -120 * y))
                      path.addLine(to: CGPoint(x: 134 * x, y: -120 * y))
                      path.addLine(to: CGPoint(x: 134 * x, y: -110 * y))
                      path.addLine(to: CGPoint(x: 136 * x, y: -110 * y))
                      path.addLine(to: CGPoint(x: 136 * x, y: -102 * y))
                      path.addLine(to: CGPoint(x: 138 * x, y: -102 * y))
                      path.addLine(to: CGPoint(x: 138 * x, y: -95 * y))
                      path.addLine(to: CGPoint(x: 140 * x, y: -95 * y))
                      path.addLine(to: CGPoint(x: 142 * x, y: -23 * y))
                      path.addLine(to: CGPoint(x: 144 * x, y: -23 * y))
                      path.addLine(to: CGPoint(x: 144 * x, y: -19 * y))
                      path.addLine(to: CGPoint(x: 147 * x, y: -19 * y))
                      path.addLine(to: CGPoint(x: 147 * x, y: -12 * y))
                      path.addLine(to: CGPoint(x: 150 * x, y: -12 * y))
                      path.addLine(to: CGPoint(x: 150 * x, y: -6 * y))
                      path.addLine(to: CGPoint(x: 153 * x, y: -6 * y))
                      path.addLine(to: CGPoint(x: 153 * x, y: -37 * y))
                      path.addLine(to: CGPoint(x: 155 * x, y: -37 * y))
                      path.addLine(to: CGPoint(x: 155 * x, y: -84 * y))
                      path.addLine(to: CGPoint(x: 158 * x, y: -84 * y))
                      path.addLine(to: CGPoint(x: 173 * x, y: -99 * y))
                      path.addLine(to: CGPoint(x: 176 * x, y: -99 * y))
                      path.addLine(to: CGPoint(x: 176 * x, y: -30 * y))
                      path.addLine(to: CGPoint(x: 180 * x, y: -30 * y))
                      path.addLine(to: CGPoint(x: 180 * x, y: -35 * y))
                      path.addLine(to: CGPoint(x: 184 * x, y: -35 * y))
                      path.addLine(to: CGPoint(x: 184 * x, y: -72 * y))
                      path.addLine(to: CGPoint(x: 187 * x, y: -72 * y))
                      path.addLine(to: CGPoint(x: 202 * x, y: -87 * y))
                      path.addLine(to: CGPoint(x: 205 * x, y: -87 * y))
                      path.addLine(to: CGPoint(x: 205 * x, y: -24 * y))
                      path.addLine(to: CGPoint(x: 208 * x, y: -24 * y))
                      path.addLine(to: CGPoint(x: 215 * x, y: -17 * y))
                      path.addLine(to: CGPoint(x: 217 * x, y: -17 * y))
                      path.addLine(to: CGPoint(x: 217 * x, y: -20 * y))
                      path.addLine(to: CGPoint(x: 218 * x, y: -20 * y))
                      path.addLine(to: CGPoint(x: 218 * x, y: -46 * y))
                      path.addLine(to: CGPoint(x: 226 * x, y: -49 * y))
                      path.addLine(to: CGPoint(x: 228 * x, y: -61 * y))
                      path.addLine(to: CGPoint(x: 230 * x, y: -49 * y))
                      path.addLine(to: CGPoint(x: 238 * x, y: -46 * y))
                      path.addLine(to: CGPoint(x: 238 * x, y: -31 * y))
                      path.addLine(to: CGPoint(x: 240 * x, y: -31 * y))
                      path.addLine(to: CGPoint(x: 242 * x, y: -31 * y))
                      path.addLine(to: CGPoint(x: 242 * x, y: -106 * y))
                      path.addLine(to: CGPoint(x: 246 * x, y: -157 * y))
                      path.addLine(to: CGPoint(x: 248 * x, y: -157 * y))
                      path.addLine(to: CGPoint(x: 248 * x, y: -159 * y))
                      path.addLine(to: CGPoint(x: 253 * x, y: -161 * y))
                      path.addLine(to: CGPoint(x: 254 * x, y: -216 * y))
                      path.addLine(to: CGPoint(x: 255 * x, y: -161 * y))
                      path.addLine(to: CGPoint(x: 260 * x, y: -159 * y))
                      path.addLine(to: CGPoint(x: 260 * x, y: -157 * y))
                      path.addLine(to: CGPoint(x: 262 * x, y: -157 * y))
                      path.addLine(to: CGPoint(x: 266 * x, y: -106 * y))
                      path.addLine(to: CGPoint(x: 266 * x, y: -31 * y))
                      path.addLine(to: CGPoint(x: 267 * x, y: -31 * y))
                      path.addLine(to: CGPoint(x: 267 * x, y: -22 * y))
                      path.addLine(to: CGPoint(x: 269 * x, y: -22 * y))
                      path.addLine(to: CGPoint(x: 272 * x, y: -30 * y))
                      path.addLine(to: CGPoint(x: 274 * x, y: -30 * y))
                      path.addLine(to: CGPoint(x: 274 * x, y: -56 * y))
                      path.addLine(to: CGPoint(x: 277 * x, y: -56 * y))
                      path.addLine(to: CGPoint(x: 277 * x, y: -66 * y))
                      path.addLine(to: CGPoint(x: 279 * x, y: -68 * y))
                      path.addLine(to: CGPoint(x: 280 * x, y: -87 * y))
                      path.addLine(to: CGPoint(x: 280 * x, y: -68 * y))
                      path.addLine(to: CGPoint(x: 282 * x, y: -66 * y))
                      path.addLine(to: CGPoint(x: 282 * x, y: -56 * y))
                      path.addLine(to: CGPoint(x: 285 * x, y: -56 * y))
                      path.addLine(to: CGPoint(x: 285 * x, y: -30 * y))
                      path.addLine(to: CGPoint(x: 287 * x, y: -30 * y))
                      path.addLine(to: CGPoint(x: 290 * x, y: -22 * y))
                      path.addLine(to: CGPoint(x: 292 * x, y: -22 * y))
                      path.addLine(to: CGPoint(x: 292 * x, y: -37 * y))
                      path.addLine(to: CGPoint(x: 293 * x, y: -37 * y))
                      path.addLine(to: CGPoint(x: 293 * x, y: -97 * y))
                      path.addLine(to: CGPoint(x: 295 * x, y: -97 * y))
                      path.addLine(to: CGPoint(x: 295 * x, y: -98 * y))
                      path.addLine(to: CGPoint(x: 297 * x, y: -98 * y))
                      path.addLine(to: CGPoint(x: 297 * x, y: -99 * y))
                      path.addLine(to: CGPoint(x: 300 * x, y: -102 * y))
                      path.addLine(to: CGPoint(x: 307 * x, y: -102 * y))
                      path.addLine(to: CGPoint(x: 310 * x, y: -99 * y))
                      path.addLine(to: CGPoint(x: 310 * x, y: -98 * y))
                      path.addLine(to: CGPoint(x: 312 * x, y: -98 * y))
                      path.addLine(to: CGPoint(x: 312 * x, y: -97 * y))
                      path.addLine(to: CGPoint(x: 314 * x, y: -97 * y))
                      path.addLine(to: CGPoint(x: 314 * x, y: -37 * y))
                      path.addLine(to: CGPoint(x: 316 * x, y: -37 * y))
                      path.addLine(to: CGPoint(x: 316 * x, y: -33 * y))
                      path.addLine(to: CGPoint(x: 319 * x, y: -36 * y))
                      path.addLine(to: CGPoint(x: 334 * x, y: -31 * y))
                      path.addLine(to: CGPoint(x: 334 * x, y: -27 * y))
                      path.addLine(to: CGPoint(x: 337 * x, y: -27 * y))
                      path.addLine(to: CGPoint(x: 337 * x, y: -8 * y))
                      path.addLine(to: CGPoint(x: 349 * x, y: -6 * y))
                      path.addLine(to: CGPoint(x: 349 * x, y: -8 * y))
                      path.addLine(to: CGPoint(x: 350 * x, y: -8 * y))
                      path.addLine(to: CGPoint(x: 350 * x, y: -10 * y))
                      path.addLine(to: CGPoint(x: 353 * x, y: -10 * y))
                      path.addLine(to: CGPoint(x: 353 * x, y: -20 * y))
                      path.addLine(to: CGPoint(x: 354 * x, y: -20 * y))
                      path.addLine(to: CGPoint(x: 354 * x, y: -39 * y))
                      path.addLine(to: CGPoint(x: 353 * x, y: -40 * y))
                      path.addLine(to: CGPoint(x: 353 * x, y: -45 * y))
                      path.addLine(to: CGPoint(x: 352 * x, y: -48 * y))
                      path.addLine(to: CGPoint(x: 352 * x, y: -50 * y))
                      path.addLine(to: CGPoint(x: 350 * x, y: -52 * y))
                      path.addLine(to: CGPoint(x: 350 * x, y: -54 * y))
                      path.addLine(to: CGPoint(x: 352 * x, y: -56 * y))
                      path.addLine(to: CGPoint(x: 353 * x, y: -56 * y))
                      path.addLine(to: CGPoint(x: 353 * x, y: -57 * y))
                      path.addLine(to: CGPoint(x: 352 * x, y: -57 * y))
                      path.addLine(to: CGPoint(x: 352 * x, y: -65 * y))
                      path.addLine(to: CGPoint(x: 351 * x, y: -66 * y))
                      path.addLine(to: CGPoint(x: 351 * x, y: -70 * y))
                      path.addLine(to: CGPoint(x: 350 * x, y: -70 * y))
                      path.addLine(to: CGPoint(x: 350 * x, y: -72 * y))
                      path.addLine(to: CGPoint(x: 351 * x, y: -72 * y))
                      path.addLine(to: CGPoint(x: 352 * x, y: -72 * y))
                      path.addLine(to: CGPoint(x: 351 * x, y: -74 * y))
                      path.addLine(to: CGPoint(x: 351 * x, y: -75 * y))
                      path.addLine(to: CGPoint(x: 353 * x, y: -77 * y))
                      path.addLine(to: CGPoint(x: 355 * x, y: -75 * y))
                      path.addLine(to: CGPoint(x: 355 * x, y: -74 * y))
                      path.addLine(to: CGPoint(x: 354 * x, y: -72 * y))
                      path.addLine(to: CGPoint(x: 356 * x, y: -72 * y))
                      path.addLine(to: CGPoint(x: 356 * x, y: -70 * y))
                      path.addLine(to: CGPoint(x: 355 * x, y: -70 * y))
                      path.addLine(to: CGPoint(x: 355 * x, y: -66 * y))
                      path.addLine(to: CGPoint(x: 354 * x, y: -65 * y))
                      path.addLine(to: CGPoint(x: 354 * x, y: -61 * y))
                      path.addLine(to: CGPoint(x: 356 * x, y: -59 * y))
                      path.addLine(to: CGPoint(x: 356 * x, y: -56 * y))
                      path.addLine(to: CGPoint(x: 357 * x, y: -56 * y))
                      path.addLine(to: CGPoint(x: 357 * x, y: -54 * y))
                      path.addLine(to: CGPoint(x: 359 * x, y: -54 * y))
                      path.addLine(to: CGPoint(x: 359 * x, y: -59 * y))
                      path.addLine(to: CGPoint(x: 357 * x, y: -59 * y))
                      path.addLine(to: CGPoint(x: 357 * x, y: -60 * y))
                      path.addLine(to: CGPoint(x: 359 * x, y: -60 * y))
                      path.addLine(to: CGPoint(x: 357 * x, y: -62 * y))
                      path.addLine(to: CGPoint(x: 357 * x, y: -63 * y))
                      path.addLine(to: CGPoint(x: 359 * x, y: -61 * y))
                      path.addLine(to: CGPoint(x: 361 * x, y: -61 * y))
                      path.addLine(to: CGPoint(x: 361 * x, y: -63 * y))
                      path.addLine(to: CGPoint(x: 362 * x, y: -63 * y))
                      path.addLine(to: CGPoint(x: 362 * x, y: -61 * y))
                      path.addLine(to: CGPoint(x: 364 * x, y: -61 * y))
                      path.addLine(to: CGPoint(x: 366 * x, y: -63 * y))
                      path.addLine(to: CGPoint(x: 366 * x, y: -62 * y))
                      path.addLine(to: CGPoint(x: 364 * x, y: -60 * y))
                      path.addLine(to: CGPoint(x: 366 * x, y: -60 * y))
                      path.addLine(to: CGPoint(x: 366 * x, y: -59 * y))
                      path.addLine(to: CGPoint(x: 364 * x, y: -59 * y))
                      path.addLine(to: CGPoint(x: 364 * x, y: -53 * y))
                      path.addLine(to: CGPoint(x: 367 * x, y: -50 * y))
                      path.addLine(to: CGPoint(x: 367 * x, y: -48 * y))
                      path.addLine(to: CGPoint(x: 368 * x, y: -47 * y))
                      path.addLine(to: CGPoint(x: 371 * x, y: -50 * y))
                      path.addLine(to: CGPoint(x: 372 * x, y: -49 * y))
                      path.addLine(to: CGPoint(x: 374 * x, y: -49 * y))
                      path.addLine(to: CGPoint(x: 374 * x, y: -47 * y))
                      path.addLine(to: CGPoint(x: 373 * x, y: -47 * y))
                      path.addLine(to: CGPoint(x: 373 * x, y: -45 * y))
                      path.addLine(to: CGPoint(x: 371 * x, y: -43 * y))
                      path.addLine(to: CGPoint(x: 369 * x, y: -43 * y))
                      path.addLine(to: CGPoint(x: 369 * x, y: -39 * y))
                      path.addLine(to: CGPoint(x: 368 * x, y: -39 * y))
                      path.addLine(to: CGPoint(x: 368 * x, y: -20 * y))
                      path.addLine(to: CGPoint(x: 369 * x, y: -20 * y))
                      path.addLine(to: CGPoint(x: 369 * x, y: -10 * y))
                      path.addLine(to: CGPoint(x: 372 * x, y: -10 * y))
                      path.addLine(to: CGPoint(x: 372 * x, y: -7 * y))
                      path.addLine(to: CGPoint(x: 374 * x, y: -7 * y))
                      path.addLine(to: CGPoint(x: 374 * x, y: -2 * y))
                      path.addLine(to: CGPoint(x: 387 * x, y: -2 * y))
                      path.addLine(to: CGPoint(x: 387 * x, y: 0 * y))
        }
         
        .fill(cityColor)
        .opacity(opacity)
        .animation(.easeOut(duration: 3))
    }
        
    }
}

struct SecondHouse_Previews: PreviewProvider {
    static var previews: some View {
        ZStack{
            NYcity(cityColor: .constant(.black),
                   dark: true,
                   x: 1,
                   y: 1,
                   opacity: 1)
                .offset(x: 10, y: 400)
            
          
            
        }
        
    }
}
